config/routes.rb
Rails.application.routes.draw do
  resources :gists

  get 'sessions/new'
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'sessions#destroy', as: 'signout'

  root to: 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gist.rb
class Gist
  include ActiveModel::Model

  attr_accessor :id, :description, :filename, :content

  def initialize(id, description = nil, filename = nil, content = nil)
    @id = id
    @description = description
    @filename = filename
    @content = content
  end

  def persisted?
    false
  end
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth)
    find_or_initialize_by(provider: auth.provider, uid: auth.uid).tap do |user|
      user.email       = auth.info.email
      user.uid         = auth.uid
      user.provider    = auth.provider
      user.avatar_url  = auth.info.image
      user.username    = auth.info.name
      user.oauth_token = auth.credentials.token
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    session[:user_id].nil? ? nil : User.find(session[:user_id])
  end

  def render_error(exception)
    flash[:error] = exception.message
    redirect_to root_path
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :authorize_user
  rescue_from Github::ApiError, with: :render_error

  def index
    @gists = Github::Gateway.get_gists(current_user)
  end

  def new
    @gist = Gist.new(nil)
  end

  def create
    if Github::Gateway.create(gist_params.to_json, current_user)
      redirect_to gists_path, notice: 'Gist was successfully created.'
    else
      render :new
    end
  end

  def edit
    @gist = Github::Gateway.get_gist(params[:id], current_user)
  end

  def update
    Github::Gateway.update_gist(params[:id], params[:gist].to_json, current_user)
    redirect_to gists_path, notice: 'Gist was successfully updated.'
  end

  def destroy
    Github::Gateway.delete_gist(params[:id], current_user)
    redirect_to gists_path, notice: 'Gist was successfully deleted.'
  end

  private

  def gist_params
    params.require(:gist).permit(:description, :filename, :content)
  end

  def authorize_user
    redirect_to root_url unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.from_omniauth(request.env['omniauth.auth'])
    return unless user.valid?

    session[:user_id] = user.id
    redirect_to gists_path
  end

  def destroy
    reset_session
    redirect_to request.referer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then 'alert alert-info'
    when 'success' then 'alert alert-success'
    when 'error' then 'alert alert-danger'
    when 'alert' then 'alert alert-warning'
    end
  end
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/gists/edit.html.erb
<h3>Edit Gist</h3>
<%= bootstrap_form_for(@gist, url: gist_path(@gist.id), method: :patch, layout: :horizontal) do |f| %>
  <%= f.text_field :description %>
  <%= f.text_field :filename %>
  <%= f.text_area :content %>
  <%= f.submit "Update Gist", class: 'btn btn-primary' %><%= link_to 'Back', gists_path, class: 'btn btn-primary' %>
<% end %>

app/views/gists/index.html.erb
<h1>Private Gists</h1>

<% @gists.each do |gist| %>
  <div class="row">
    <div class="col-md-6">
      <%= link_to gist.description, edit_gist_path(gist.id) %>
    </div>
    <div class="col-md-6">
      <%= link_to 'Delete',  { action: :destroy, id: gist.id }, method: :delete, class: 'btn btn-sm btn-danger delete' %>
    </div>
  </div>
<% end %>

<%= link_to 'New gist', new_gist_path, class: 'btn btn-primary' %>

app/views/gists/new.html.erb
<h3>New Gist</h3>
<%= bootstrap_form_for(@gist, layout: :horizontal) do |f| %>
  <%= f.text_field :description, placeholder: 'Gist description....' %>
  <%= f.text_field :filename, placeholder: 'Filename including extension....' %>
  <%= f.text_area :content %>
  <%= f.submit class: 'btn btn-primary' %><%= link_to 'Back', gists_path, class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Github Gists</title>
    <%= csrf_meta_tags %>
    <% if current_user.present? %>
      <%= button_to "Sign Out", signout_path, method: :delete, class: 'btn btn-primary right' %>
    <% end %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
        <%= value %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>